# Generated by Django 2.0.1 on 2018-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_zh', models.CharField(max_length=200)),
                ('company_name_en', models.CharField(max_length=200)),
                ('report_year', models.IntegerField()),
                ('setup_year', models.CharField(max_length=200)),
                ('setup_place', models.CharField(max_length=200)),
                ('business', models.CharField(max_length=1000)),
                ('organization_chart', models.ImageField(upload_to='')),
            ],
        ),
    ]
