# Generated by Django 2.0.1 on 2018-02-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='setup_year',
            field=models.IntegerField(),
        ),
    ]
